### ISSUE TITLE
Thanks and question regarding licence

### ISSUE THREAD

**Issue by philipptrenz** [KiOui/SunPortal#1]
Hi @KiOui,

I found your repo yesterday and it's just perfect for my needs. So many thanks to you for sharing your code! 

I forked your repo and already made some adjustments for my needs like multi inverter support and some styling and naming things. I also plan to migrate your code to node.js to be able to load data in the background and just push updates via websockets. In this case I can trigger SBFspot from within the backend code and update the clients afterwards.

Anyways, I would like to share your code with my changes under an appropriate licence. In general I use the MIT licence, would this be okay for you?

Best regards,
Philipp

**Comment by KiOui** [comment]
Hey Philipp!

Well, this is actually the first time someone uses my work, do with it as you want! A MIT license would be okay.

Regards,

Lars

**Comment by philipptrenz** [comment]
Hi Lars,

okay, perfect! Thanks!

Greetings
