### ISSUE TITLE
FAILS, Step 1

### ISSUE THREAD

**Issue by halfagascan** [KiOui/SunPortal#6]
Linux thunder 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash
SBFspot Configuration Tool V1.2.1
grep: /proc/device-tree/model: No such file or directory
Error: Not running on Raspberry Pi.

**Comment by ErikvanTrijp** [comment]
Hi, i get error ERROR: Head "https://docker.pkg.github.com/v2/kioui/sunportal/sunportal/manifests/latest": no basic auth credentials

Any thoughts on this?

**Comment by KiOui** [comment]
> Linux thunder 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
> 
> curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash SBFspot Configuration Tool V1.2.1 grep: /proc/device-tree/model: No such file or directory Error: Not running on Raspberry Pi.

This is something wrong with the guide for installing SBFSpot, please search for another guide on the internet or contact the developers of SBFSpot for this question.

**Comment by KiOui** [comment]
> Hi, i get error ERROR: Head "https://docker.pkg.github.com/v2/kioui/sunportal/sunportal/manifests/latest": no basic auth credentials
> 
> Any thoughts on this?

This is a currently known issue with GitHub packages, you could instead try to change line 17 in `docker-compose.yml` to:
```
        image: "larsvanrhijn/sunportal:latest"
```
